spring.main.banner-mode=off

server.port=8085

frontend.host=localhost
frontend.port=8088
frontend.url=http://${frontend.host}:${frontend.port}

#database config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/coffee-house-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#jwt token
#unit of expiration time -> minutes
jwt.token.secret=tokenSecretKey
jwt.token.expiration=1440

#log4j2
logging.config=classpath:log4j2.xml

#swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tagsSorter=alpha
api.title=Coffee Houses App
api.version=v1
api.description=API for Coffee House App
dev.server=http://localhost:${server.port}
